### PR TITLE
adding click open functionality for cxtmenu

### PR DESCRIPTION
**Pull request by kamranjon**
This allows a click-open functionality similar to the neo4j-browser

### CODE REVIEW

**Comment by maxkfranz** [comment]
Does this work in conjunction with other events, e.g. can I specify `click cxttapstart`?  If it breaks swiping (the main usecase for the extension), it could be a problem.

**Comment by kamranjon** [comment]
This currently only changes behavior if click is defined as the only openMenuEvent - so it should not cause issues with swiping interactions

**Comment by maxkfranz** [comment]
@kamranjon It seems to work OK for me even with `openMenuEvents: 'cxttapstart taphold click'`.  I noticed some things though:

1. `click` should probably be `tap` to be device agnostic.
1. `click` allows you to click the background or another element when doing the second click to select the menu item.  This means that it could bring up the menu for another node or bring up some other UI in an app.  It would be good if this could be prevented somehow.

**Comment by kamranjon** [comment]
@maxkfranz thanks for the feedback - I thought about this for tap - I will implement that - and for the second point I will look into preventing the event. Thanks.

**Pull request closed without merging**
