### PR TITLE
Support for dynamic context menu's

### PR DESCRIPTION
**Pull request by janblok**
Small addition to have dynamic menu's support on each element

### CODE REVIEW

**Comment by maxkfranz** [comment]
Thanks; I'll take a look at this when I'm back on the week of 24 Nov

**Comment by janblok** [comment]
Any updates on this?

**Comment by maxkfranz** [comment]
It's been merged into 2.3 with fixes to resolve some issues brought on by the changes.  It's unnecessary to have two options, so only `options.commands` is used.

**Comment by janblok** [comment]
Ah nice! assumed having one option to support both could be confusing for users.
But this is for sure cleaner.

**Pull request merged**
