### PR TITLE
Adaptative menu size improvement with adaptative spotlight radius

### PR DESCRIPTION
**Pull request by tristanidoux**
Adaptative menu size improvement with adaptative spotlight radius support
- Spotlight radius will now be equal to the node rendered size  if no min|maxSpotlightRadius is specified.

### CODE REVIEW

**Comment by maxkfranz** [comment]
Could you list out the improvements (new features, etc.) in the PR?

**Comment by tristanidoux** [comment]
Description updated.

**Comment by maxkfranz** [comment]
The previous PR seems to have an issue.  The menu contents are no longer properly placed.  They're off centre.  This doesn't seem to be fixed in this PR.

Screen Shot 2020-10-02 at 14 27 51

This PR creates another issue.  The menu size randomly changes:

Untitled24

**Comment by tristanidoux** [comment]
My bad, sorry I had a typo and fixed it now. 
The main goal of the PR is to have an adaptative spotlight radius based on the node rendered size as the nodes size may vary during time in my application so a static radius' didn't fit my needs.

I added an option to enable the adaptative spotlight radius for the node: **adaptativeNodeSpotlightRadius**.

Changelog:
- Fix type for min|maxSpotlightRadius calculation (
- Added an options to enable/disable the adaptative spotlight radius for the node (adaptativeNodeSpotlightRadius)
- Added comments for better comprehension

Let me know if you still see errors.

**Comment by maxkfranz** [comment]
Great.  It looks like the default demo is working fine.  Since your PRs have added a set of new features that aren't showcased by the existing demo, would you create a new demo that shows off these new features?

- [ ] Create a demo-adaptive.html file.  Copy the existing demo and adjust the extension options and the stylesheet to show off how the new features are useful.  It could include nodes of different sizes or changing sizes.
- [ ] Create a symlink to the new demo file under the `pages` directory so that the new demo gets deployed to gh-pages on release.

**Comment by maxkfranz** [comment]
I’ll plan to review this tomorrow.  If there are no issues, I’ll just push a release.

**Comment by maxkfranz** [comment]
> Great. It looks like the default demo is working fine. Since your PRs have added a set of new features that aren't showcased by the existing demo, would you create a new demo that shows off these new features?
> 
> * [ ]  Create a demo-adaptive.html file.  Copy the existing demo and adjust the extension options and the stylesheet to show off how the new features are useful.  It could include nodes of different sizes or changing sizes.
> * [ ]  Create a symlink to the new demo file under the `pages` directory so that the new demo gets deployed to gh-pages on release.

@tristanidoux, have you had a chance to put together a small demo of your new features?

**Comment by tristanidoux** [comment]
@maxkfranz Sorry, it's a crazy week at work. I will try to create a small demo this week-end.

**Comment by maxkfranz** [comment]
@tristanidoux, great.  I'll set aside some time on Monday to release.  Thanks

**Comment by tristanidoux** [comment]
@maxkfranz It should be good. I only created nodes of different sizes with `adaptativeSpotlightRadius` enabled or not to show the difference.
Let met know if it's enough or not.

**Comment by maxkfranz** [comment]
It looks great.  A link from the readme would help people to find the live demo.

I'm noticing an issue with small nodes, but otherwise things look fine.  The arrow gets weird for small nodes:

sm-node-cxtmenu

**Comment by tristanidoux** [comment]
Will try to look into the arrow and add a link in README as soon as possible.

**Comment by maxkfranz** [comment]
OK, if the issue for the small spotlight looks too time consuming, then maybe we could just set a hard limit on the minimum size of the spotlight.  I think that would be good enough for now, and then we can just publish a release based on these improvements.

**Comment by tristanidoux** [comment]
- Fix indicator arrow for node size < indicatorSize defined in options
- Linked adaptative spotlight radius features in README

**Comment by maxkfranz** [comment]
Looks good.  Released as 3.3.0

**Comment by maxkfranz** [comment]
Thanks again for the PR, @tristanidoux

**Comment by tristanidoux** [comment]
@maxkfranz No problem, thanks for this extension 😄

**Pull request merged**
